# Generated by Django 2.2.24 on 2021-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='ID_ENTIDAD',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
